export const mockProperties = [
  {
    id: 1,
    title: "Modern Apartment in Zurich",
    description:
      "Spacious 3-bedroom apartment with stunning views of Lake Zurich. Features high-end finishes, an open floor plan, and a private balcony overlooking the water.",
    price: 1250000,
    location: "Seefeld, Zurich",
    image:
      "https://media2.homegate.ch/f_auto/t_web_dp_small/listings/v2/g014/4002077433/image/af646d4e45539379f6dd2ab6a5479f91.jpg",
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    type: "apartment",
    features: ["Lake View", "Balcony", "Parking", "Elevator"],
    yearBuilt: 2018,
    energyRating: "A",
  },
  {
    id: 2,
    title: "Luxury Villa with Garden",
    description:
      "Beautiful villa with large garden and swimming pool in a quiet neighborhood. Perfect for families seeking space and privacy with easy access to the city center.",
    price: 2800000,
    location: "Lucerne, Switzerland",
    image:
      "https://media2.homegate.ch/f_auto/t_web_dp_small/listings/v2/linkauf/4002062006/image/939c46949edb880e4ce3ccbdb35488f8.jpg",
    bedrooms: 5,
    bathrooms: 3,
    area: 250,
    type: "house",
    features: ["Swimming Pool", "Garden", "Garage", "Fireplace"],
    yearBuilt: 2010,
    energyRating: "B",
  },
  {
    id: 3,
    title: "Cozy Studio in City Center",
    description:
      "Modern studio apartment in the heart of Basel, close to all amenities. Ideal for young professionals or as an investment property with excellent rental potential.",
    price: 650000,
    location: "Basel, Switzerland",
    image:
      "https://media2.homegate.ch/f_auto/t_web_dp_small/listings/v2/hgonif/4002049539/image/1ee92fd13982f99bbd64bbc8b07a2779.jpg",
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
    type: "apartment",
    features: ["City Center", "Public Transport", "Renovated"],
    yearBuilt: 2015,
    energyRating: "B",
  },
  {
    id: 4,
    title: "Family Home with Garden",
    description:
      "Spacious family home with garden, perfect for growing families. Located in a quiet residential area with excellent schools nearby and easy commute to the city.",
    price: 1450000,
    location: "Bern, Switzerland",
    image:
      "https://media2.homegate.ch/f_auto/t_web_dp_small/listings/v2/hgonif/4002025621/image/4e716f8419f4cbdc6f311497897d8229.jpg",
    bedrooms: 4,
    bathrooms: 2,
    area: 180,
    type: "house",
    features: ["Garden", "Terrace", "Basement", "Quiet Area"],
    yearBuilt: 2005,
    energyRating: "C",
  },
  {
    id: 5,
    title: "Penthouse with Terrace",
    description:
      "Luxurious penthouse with large terrace and panoramic views of the city and mountains. Features premium finishes, floor-to-ceiling windows, and a private elevator.",
    price: 1950000,
    location: "Geneva, Switzerland",
    image: "/placeholder.svg?height=400&width=600",
    bedrooms: 3,
    bathrooms: 2,
    area: 150,
    type: "apartment",
    features: ["Panoramic View", "Terrace", "Private Elevator", "Smart Home"],
    yearBuilt: 2020,
    energyRating: "A+",
  },
  {
    id: 6,
    title: "Mountain Chalet",
    description:
      "Traditional Swiss chalet with modern amenities in a scenic location. Perfect as a holiday home or for those seeking the tranquility of mountain living.",
    price: 1750000,
    location: "Zermatt, Switzerland",
    image: "/placeholder.svg?height=400&width=600",
    bedrooms: 4,
    bathrooms: 3,
    area: 200,
    type: "house",
    features: ["Mountain View", "Fireplace", "Wooden Structure", "Ski Access"],
    yearBuilt: 2008,
    energyRating: "B",
  },
  {
    id: 7,
    title: "Riverside Apartment",
    description:
      "Elegant apartment along the Rhine river with beautiful water views and a spacious layout. Recently renovated with high-quality materials and modern design.",
    price: 980000,
    location: "Basel, Switzerland",
    image: "/placeholder.svg?height=400&width=600",
    bedrooms: 2,
    bathrooms: 2,
    area: 95,
    type: "apartment",
    features: ["River View", "Renovated", "Balcony", "Storage Room"],
    yearBuilt: 2012,
    energyRating: "B",
  },
  {
    id: 8,
    title: "Historic Townhouse",
    description:
      "Beautifully preserved townhouse in the historic center of Bern. Combines original architectural elements with modern comforts and conveniences.",
    price: 1650000,
    location: "Bern, Switzerland",
    image: "/placeholder.svg?height=400&width=600",
    bedrooms: 3,
    bathrooms: 2,
    area: 160,
    type: "house",
    features: ["Historic Building", "High Ceilings", "Original Features", "Central Location"],
    yearBuilt: 1890,
    energyRating: "D",
  },
  {
    id: 9,
    title: "Lakefront Property",
    description:
      "Exclusive property with direct lake access and private dock. Enjoy unobstructed views and the ultimate in waterfront living in this premium location.",
    price: 3500000,
    location: "Lugano, Switzerland",
    image: "/placeholder.svg?height=400&width=600",
    bedrooms: 4,
    bathrooms: 3,
    area: 220,
    type: "house",
    features: ["Lake Access", "Private Dock", "Garden", "Guest House"],
    yearBuilt: 2015,
    energyRating: "A",
  },
  {
    id: 10,
    title: "Modern Loft in Former Factory",
    description:
      "Unique loft apartment in a converted industrial building. Features high ceilings, large windows, and an open concept design perfect for modern living.",
    price: 890000,
    location: "Zurich, Switzerland",
    image: "/placeholder.svg?height=400&width=600",
    bedrooms: 2,
    bathrooms: 2,
    area: 110,
    type: "apartment",
    features: ["Loft Style", "Industrial Design", "High Ceilings", "Open Concept"],
    yearBuilt: 2017,
    energyRating: "B",
  },
  {
    id: 11,
    title: "Alpine Retreat",
    description:
      "Secluded mountain home with breathtaking views of the Alps. Perfect for nature lovers seeking peace and quiet with easy access to hiking and skiing.",
    price: 1250000,
    location: "Grindelwald, Switzerland",
    image: "/placeholder.svg?height=400&width=600",
    bedrooms: 3,
    bathrooms: 2,
    area: 140,
    type: "house",
    features: ["Mountain View", "Hiking Access", "Wooden Structure", "Fireplace"],
    yearBuilt: 2010,
    energyRating: "B",
  },
  {
    id: 12,
    title: "City Center Duplex",
    description:
      "Stylish duplex apartment in the heart of Geneva. Features a modern design with high-end finishes and a private rooftop terrace with city views.",
    price: 1450000,
    location: "Geneva, Switzerland",
    image: "/placeholder.svg?height=400&width=600",
    bedrooms: 3,
    bathrooms: 2,
    area: 130,
    type: "apartment",
    features: ["Duplex", "Rooftop Terrace", "City View", "Modern Design"],
    yearBuilt: 2019,
    energyRating: "A",
  },
]
